"""on delete cascade

Revision ID: 48df148dae0b
Revises: 1fec114a77ae
Create Date: 2022-07-08 08:51:53.221743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48df148dae0b'
down_revision = '1fec114a77ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('tags_ibfk_1', 'tags', type_='foreignkey')
    # op.drop_constraint('tags_ibfk_2', 'tags', type_='foreignkey')
    op.create_foreign_key(None, 'tags', 'tag', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tags', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_constraint(None, 'tags', type_='foreignkey')
    # op.create_foreign_key('tags_ibfk_2', 'tags', 'tag', ['tag_id'], ['id'])
    # op.create_foreign_key('tags_ibfk_1', 'tags', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###
