"""list of blocked tokens

Revision ID: ee7cb5bad2b2
Revises: 48df148dae0b
Create Date: 2022-07-13 15:13:55.019292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee7cb5bad2b2'
down_revision = '48df148dae0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_blocklist_jti'), 'token_blocklist', ['jti'], unique=False)
    op.drop_constraint('tags_tag_id_fkey', 'tags', type_='foreignkey')
    op.drop_constraint('tags_post_id_fkey', 'tags', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('tags_post_id_fkey', 'tags', 'post', ['post_id'], ['id'])
    op.create_foreign_key('tags_tag_id_fkey', 'tags', 'tag', ['tag_id'], ['id'])
    op.drop_index(op.f('ix_token_blocklist_jti'), table_name='token_blocklist')
    op.drop_table('token_blocklist')
    # ### end Alembic commands ###
